# Generated by Django 3.2.5 on 2021-07-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_brand_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Processor_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('clock_min_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clock_max_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tdp', models.IntegerField()),
                ('socket', models.CharField(max_length=10)),
                ('core_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.corebrand')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.generation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
