# Generated by Django 3.2.5 on 2021-07-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('clock_min_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clock_max_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tdp', models.IntegerField()),
                ('socket', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=20)),
                ('core_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.corebrand')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.generation')),
            ],
        ),
        migrations.DeleteModel(
            name='Processor_Detail',
        ),
        migrations.AddField(
            model_name='product',
            name='processor_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='products.processordetail'),
        ),
    ]
