# Generated by Django 3.2.5 on 2021-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210728_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='processordetail',
            name='freq',
            field=models.DecimalField(decimal_places=2, default=3.45, max_digits=5),
            preserve_default=False,
        ),
    ]
