# Generated by Django 3.2.5 on 2021-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_processordetail_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='processordetail',
            name='external_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
