# Generated by Django 3.2.5 on 2021-08-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_processordetail_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='processordetail',
            name='proc_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
