# Generated by Django 3.2.5 on 2021-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_processordetail_proc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processordetail',
            name='proc_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/processors', verbose_name='Image'),
        ),
    ]
